sidebarPanel(
  titlePanel("Patient Characteristics"),
  radioButtons("age", "Patient Age", 
						   choices = list("<60 Years" =   0,
						 	  						  "60-70 Years" = 1,
						 		  					  "71-80 Years" = 2,
						 			  				  ">80 Years" =   3)),
  radioButtons("race", "Patient Race",
  						 choices = list("White" =     0,
						 							    "Non-white" = 1)),
  radioButtons("indication", "Indication for Procedure",
	  					 choices = list("Rest pain" =   0,
		  				 							  "Tissue loss" = 1)),
  radioButtons("cad", "History of coronary artery disease",
				   		 choices = list("None" =                                         0,
		  				 						    "History of MI, asymptomatic or stable angina" = 1,
	  					 							  "Unstable angina/MI within 6 months" =           2)),
  radioButtons("chf", "Congestive Heart Failure",
  						 choices = list("No" =  0,
	  					 						    "Yes" = 1)),
  radioButtons("copd", "COPD",
			  			 choices = list("None" =                         0,
			  			 						    "Not treated or on medication" = 1,
			  			 						    "Home oxygen" =                  2)),
  radioButtons("ckd", "Chronic kidney disease stage",
			  			 choices = list("1 (GFR >90 mL/min/1.73 m2)" =    0,
						 							    "2 (GFR 60-89 mL/min/1.73 m2)" =  1,
						 							    "3 (GFR 30-59 mL/min/1.73 m2)" =  2,
						 						      "4 (GFR 15-29 mL/min/1.73 m2)" =  3,
						 						      "5 (GFR <15 mL/min/1.73 m2)" =    4)),
  radioButtons("ambulation", "Ambulation Status",
						   choices = list("Independent" =      0,
						 						     	"With Assistance" =  1,
						 							    "Wheelchair bound" = 2,
						 							    "Bedbound" =         3)),
  radioButtons("statin", "Pre-opreative medications: Statin",
						   choices = list("No" =  0,
						 							    "Yes" = 1))
)