sidebarPanel(
  titlePanel("Patient Characteristics"),
  sliderInput("age_a", "Patient Age", min = 18, max = 90, value = 45),
  radioButtons("sex_a", "Patient Sex",
  						 choices = list("Male" = 0,
  						 							 "Female" = 1)),
  radioButtons("race_a", "Patient Race",
  						 choices = list("White" =     0,
						 							    "Non-white" = 1)),
  radioButtons("indication_a", "Indication for Procedure",
	  					 choices = list("Asymptomatic" =   0,
		  				 							  "Symptomatic" = 1,
	  					 							  "Ruptured" = 2)),
  radioButtons("proc_a", "Procedure AAA",
  						 choices = list("EVAR" = 0,
  						 								"Open Infrarenal" = 1,
  						 							  "Open Suprarenal" = 2)),
  radioButtons("diam_a", "Maximal Aorta Diameter",
  						 choices = list("<65mm" = 0,
  						 							  ">65mm" = 1)),
  radioButtons("cad_a", "History of coronary artery disease",
  						 choices = list("None" =                                         0,
  						 							 "History of MI, asymptomatic or stable angina" = 1,
  						 							 "Unstable angina/MI within 6 months" =           2)),
  radioButtons("cvd_a", "Cerebrovascular Disease",
  						 choices = list("No" =  0,
	  					 						    "Yes" = 1)),
  radioButtons("copd_a", "COPD",
			  			 choices = list("None" =                         0,
			  			 						    "Not treated or on medication" = 1,
			  			 						    "Home oxygen" =                  2)),
  radioButtons("ckd_a", "Chronic kidney disease stage",
			  			 choices = list("Cr <1.5" =  0,
						 							    "Cr 1.5-2" = 1,
						 							    "Cr >2" =    2))
)